import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

/**
 * Integrity of the combined production migration (M-AFFILIATE1, spec §24).
 *
 * `affiliate_engine_m1_combined.sql` is generated by concatenating the two
 * source migrations with a guard between them. These tests assert it stayed
 * faithful to its sources and kept the properties that make it safe to run:
 * one transaction, and an abort rather than an admin lockout.
 */

const ROOT = path.join(import.meta.dirname, "..");

const read = (p: string) => fs.readFileSync(path.join(ROOT, "supabase", p), "utf8");

const combined = read("affiliate_engine_m1_combined.sql");
const main = read("affiliate_engine_m1.sql");
const hardening = read("affiliate_engine_m1_hardening.sql");

test("the combined migration contains both source migrations verbatim", () => {
  assert.ok(
    combined.includes(main.trim()),
    "affiliate_engine_m1.sql has drifted from the combined file — regenerate it"
  );
  assert.ok(
    combined.includes(hardening.trim()),
    "affiliate_engine_m1_hardening.sql has drifted from the combined file — regenerate it"
  );
});

test("it applies atomically, so there is no window where operator columns are exposed", () => {
  const transactionStatements = combined
    .split("\n")
    .filter((line) => /^\s*(begin|commit|rollback)\s*;/i.test(line));

  assert.deepEqual(
    transactionStatements.map((s) => s.trim().toLowerCase()),
    ["begin;", "commit;"],
    "exactly one transaction — a stray commit would reopen the exposure window"
  );

  assert.ok(
    combined.indexOf("begin;") < combined.indexOf(main.trim()),
    "the transaction must open before the main migration"
  );
  assert.ok(
    combined.lastIndexOf("commit;") > combined.indexOf(hardening.trim()),
    "the transaction must close after the hardening"
  );
});

test("no CONCURRENTLY index — it cannot run inside a transaction", () => {
  assert.ok(!/concurrently/i.test(combined));
});

test("hardening comes after the main migration, never before", () => {
  assert.ok(
    combined.indexOf(main.trim()) < combined.indexOf(hardening.trim()),
    "hardening references columns the main migration creates"
  );
});

test("it aborts rather than locking the operator out of the admin", () => {
  assert.ok(
    combined.includes("insert into user_profiles"),
    "must promote an administrator before restricting writes to admins"
  );
  assert.match(
    combined,
    /raise exception[\s\S]*no administrator exists/i,
    "must abort when no admin row exists — user_profiles is empty in production"
  );
});

test("with the placeholder left in place it promotes the sole account, or aborts", () => {
  // Production has exactly one auth account, so the common path needs no
  // operator input — and no personal email lands in this public repository.
  assert.ok(combined.includes("YOUR@EMAIL.HERE"));
  assert.match(
    combined,
    /account_count <> 1/,
    "the sole-account path must be explicit"
  );
  assert.match(
    combined,
    /raise exception[\s\S]*ambiguous/i,
    "more than one auth account must abort rather than guess an administrator"
  );
});

test("an explicit address matching no account aborts", () => {
  assert.match(combined, /raise exception[\s\S]*no Supabase auth account matches/i);
});

test("the promotion runs before the admin-only policies are installed", () => {
  assert.ok(
    combined.indexOf("insert into user_profiles") < combined.indexOf("is_affiliate_admin()"),
    "promoting after the policies are live is the lockout scenario"
  );
});
