import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

/**
 * Integrity of the combined production migration (M-AFFILIATE1, spec §24).
 *
 * `affiliate_engine_m1_combined.sql` is generated by concatenating the two
 * source migrations with a guard between them. These tests assert it stayed
 * faithful to its sources and kept the properties that make it safe to run:
 * one transaction, and an abort rather than an admin lockout.
 */

const ROOT = path.join(import.meta.dirname, "..");

const read = (p: string) => fs.readFileSync(path.join(ROOT, "supabase", p), "utf8");

const combined = read("affiliate_engine_m1_combined.sql");
const main = read("affiliate_engine_m1.sql");
const hardening = read("affiliate_engine_m1_hardening.sql");

test("the combined migration contains both source migrations verbatim", () => {
  assert.ok(
    combined.includes(main.trim()),
    "affiliate_engine_m1.sql has drifted from the combined file — regenerate it"
  );
  assert.ok(
    combined.includes(hardening.trim()),
    "affiliate_engine_m1_hardening.sql has drifted from the combined file — regenerate it"
  );
});

test("it applies atomically, so there is no window where operator columns are exposed", () => {
  const transactionStatements = combined
    .split("\n")
    .filter((line) => /^\s*(begin|commit|rollback)\s*;/i.test(line));

  assert.deepEqual(
    transactionStatements.map((s) => s.trim().toLowerCase()),
    ["begin;", "commit;"],
    "exactly one transaction — a stray commit would reopen the exposure window"
  );

  assert.ok(
    combined.indexOf("begin;") < combined.indexOf(main.trim()),
    "the transaction must open before the main migration"
  );
  assert.ok(
    combined.lastIndexOf("commit;") > combined.indexOf(hardening.trim()),
    "the transaction must close after the hardening"
  );
});

test("no CONCURRENTLY index — it cannot run inside a transaction", () => {
  assert.ok(!/concurrently/i.test(combined));
});

test("hardening comes after the main migration, never before", () => {
  assert.ok(
    combined.indexOf(main.trim()) < combined.indexOf(hardening.trim()),
    "hardening references columns the main migration creates"
  );
});

test("it aborts rather than locking the operator out of the admin", () => {
  assert.ok(
    combined.includes("insert into user_profiles"),
    "must promote an administrator before restricting writes to admins"
  );
  assert.match(
    combined,
    /raise exception[\s\S]*no administrator exists/i,
    "must abort when no admin row exists — user_profiles is empty in production"
  );
});

test("with the placeholder left in place it promotes the sole account, or aborts", () => {
  // Production has exactly one auth account, so the common path needs no
  // operator input — and no personal email lands in this public repository.
  assert.ok(combined.includes("YOUR@EMAIL.HERE"));
  assert.match(
    combined,
    /account_count <> 1/,
    "the sole-account path must be explicit"
  );
  assert.match(
    combined,
    /raise exception[\s\S]*ambiguous/i,
    "more than one auth account must abort rather than guess an administrator"
  );
});

test("an explicit address matching no account aborts", () => {
  assert.match(combined, /raise exception[\s\S]*no Supabase auth account matches/i);
});

test("the promotion runs before the admin-only policies are installed", () => {
  assert.ok(
    combined.indexOf("insert into user_profiles") < combined.indexOf("is_affiliate_admin()"),
    "promoting after the policies are live is the lockout scenario"
  );
});

test("no state is passed between statements, so the file is re-runnable", () => {
  // A temporary table spanning ~700 lines of migration is session-scoped and
  // dropped at commit. On 2026-08-24 that produced
  // `relation "_m_affiliate1_config" does not exist` AFTER the real work had
  // already committed — a successful migration that looked like a failure.
  const executable = combined
    .split("\n")
    .filter((line) => !line.trim().startsWith("--"))
    .join("\n");

  assert.ok(
    !/create\s+temporary\s+table/i.test(executable),
    "no temporary table: nothing may need to survive between statements"
  );
  assert.ok(
    !/_m_affiliate1_config/.test(executable),
    "the old cross-statement config table must not return"
  );
});

test("the administrator address is a local variable inside the block that uses it", () => {
  assert.match(
    combined,
    /configured\s+constant\s+text\s*:=\s*'YOUR@EMAIL\.HERE'/,
    "the address must be declared where it is read"
  );
});

test("every statement is idempotent, so a second run is safe", () => {
  const executable = combined
    .split("\n")
    .filter((line) => !line.trim().startsWith("--"))
    .join("\n");

  // Bare `create table` / `create policy` would fail on a re-run.
  const bareCreateTable = /create\s+table\s+(?!if\s+not\s+exists)/i.test(executable);
  const bareCreatePolicy = executable
    .split("\n")
    .some((line, index, lines) => {
      if (!/^\s*create\s+policy/i.test(line)) return false;
      // Each create policy must be preceded by a matching drop policy.
      return !lines.slice(Math.max(0, index - 3), index).some((prior) =>
        /drop\s+policy\s+if\s+exists/i.test(prior)
      );
    });

  assert.ok(!bareCreateTable, "every create table needs `if not exists`");
  assert.ok(!bareCreatePolicy, "every create policy needs a preceding `drop policy if exists`");
});
